openapi: 3.0.0
info:
  title: Class Method TODO App API
  description: Class Method TODO App API Specification.
  version: 1.0.0

paths:
  /todos:
    get:
      summary: Retrieve List Of TODO
      description: Retrieve List Of TODO.
      responses:
        '200':
          description: List Of TODO retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    content:
                      type: string
                    expiration:
                      type: string
                    status:
                      type: string
        '500':
          description: Internal Server Error.
  /todo:
    post:
      summary: Create TODO
      description: Create TODO.
      responses:
        '200':
          description: TODO created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
                  expiration:
                    type: string
                  status:
                    type: string
        '500':
          description: Internal Server Error.
  /todo/{todoId}:
    put:
      summary: Update TODO
      description: Update TODO.
      responses:
        '200':
          description: TODO updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
                  expiration:
                    type: string
                  status:
                    type: string
        '404':
          description: TODO is not found.
        '500':
          description: Internal Server Error.
    delete:
      summary: Delete TODO
      description: Delete TODO.
      responses:
        '200':
          description: TODO deleted successfully.
        '404':
          description: TODO is not found.
        '500':
          description: Internal Server Error.
