openapi: 3.0.0
info:
  title: Class Method TODO App API
  description: Class Method TODO App API Specification.
  version: 1.0.0
security:
  - api_key: []
paths:
  /tasks:
    get:
      summary: Retrieve Tasks
      description: Retrieve Tasks.
      responses:
        '200':
          description: Tasks retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: '1692757218707'
                    title:
                      type: string
                      example: 'タスクのタイトル'
                    content:
                      type: string
                      example: 'タスクの内容'
                    expiration:
                      type: string
                      example: '2023-08-31T10:00'
                    status:
                      type: string
                      example: 'TODO'
        '403':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Forbidden.'
        '500':
          description: Internal Server Error.
  /task:
    post:
      summary: Create Task
      description: Create Task.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - expiration
              properties:
                title:
                  type: string
                  example: 'タスクのタイトル'
                content:
                  type: string
                  example: 'タスクの内容'
                expiration:
                  type: string
                  example: '2023-08-31T10:00'
      responses:
        '200':
          description: Task created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: '1692757218707'
                  title:
                    type: string
                    example: 'タスクのタイトル'
                  content:
                    type: string
                    example: 'タスクの内容'
                  expiration:
                    type: string
                    example: '2023-08-31T10:00'
                  status:
                    type: string
                    example: 'TODO'
        '400':
          description: Invalid Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'title in requestBody is required.'
        '403':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Forbidden.'
        '500':
          description: Internal Server Error.
  /task/{taskId}:
    put:
      summary: Update Task
      description: Update Task.
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - expiration
                - status
              properties:
                title:
                  type: string
                  example: 'タスクのタイトル'
                content:
                  type: string
                  example: 'タスクの内容'
                expiration:
                  type: string
                  example: '2023-08-31T10:00'
                status:
                  type: string
                  example: 'DONE'
      responses:
        '200':
          description: Task updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: '1692757218707'
                  title:
                    type: string
                    example: 'タスクのタイトル'
                  content:
                    type: string
                    example: 'タスクの内容'
                  expiration:
                    type: string
                    example: '2023-08-31T10:00'
                  status:
                    type: string
                    example: 'TODO'
        '400':
          description: Invalid Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'title in requestBody is required.'
        '403':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Forbidden.'
        '404':
          description: Task is not found.
        '500':
          description: Internal Server Error.
    delete:
      summary: Delete Task
      description: Delete Task.
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task deleted successfully.
        '400':
          description: Invalid Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'tastId in pathParameters is required.'
        '403':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Forbidden.'
        '404':
          description: Task is not found.
        '500':
          description: Internal Server Error.
components:
  securitySchemes:
    api_key:
      type: 'apiKey'
      name: 'x-api-key'
      in: 'header'
